// <auto-generated />
using System;
using CoreCare.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoreCare.Migrations
{
    [DbContext(typeof(CoreCareDbContext))]
    [Migration("20260318170916_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("CoreCare.Models.RegistroBenchmark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("CpuClock")
                        .HasColumnType("REAL");

                    b.Property<float>("CpuLoad")
                        .HasColumnType("REAL");

                    b.Property<float>("CpuTemp")
                        .HasColumnType("REAL");

                    b.Property<float>("DiskLoad")
                        .HasColumnType("REAL");

                    b.Property<float>("DiskReadRate")
                        .HasColumnType("REAL");

                    b.Property<float>("DiskWriteRate")
                        .HasColumnType("REAL");

                    b.Property<float>("GpuLoad")
                        .HasColumnType("REAL");

                    b.Property<float>("GpuTemp")
                        .HasColumnType("REAL");

                    b.Property<float>("RamLoad")
                        .HasColumnType("REAL");

                    b.Property<float>("RamUsed")
                        .HasColumnType("REAL");

                    b.Property<float>("Score")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RegistrosBenchmark");
                });
#pragma warning restore 612, 618
        }
    }
}
